# Ex -

### Introduction:

This time you will create a data 

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import numpy as np
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called

In [2]:
chip = pd.read_csv("chipotle.tsv", sep="\t")
chip.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [3]:
chip.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

In [4]:
chip

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [8]:
price_changer=lambda x:float(x[1:])
chip.item_price=chip.item_price.apply(price_changer)
chip.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   float64
dtypes: float64(1), int64(2), object(2)
memory usage: 180.7+ KB

In [10]:
chip.choice_description.fillna("Not available", inplace=True)
chip.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  4622 non-null   object
 4   item_price          4622 non-null   float64
dtypes: float64(1), int64(2), object(2)
memory usage: 180.7+ KB

In [11]:
chip.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,Not available,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,Not available,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98

In [12]:
chip.nunique()

order_id              1834
quantity                 9
item_name               50
choice_description    1044
item_price              78
dtype: int64

In [13]:
chip.item_name.value_counts()

item_name
Chicken Bowl                             726
Chicken Burrito                          553
Chips and Guacamole                      479
Steak Burrito                            368
Canned Soft Drink                        301
Steak Bowl                               211
Chips                                    211
Bottled Water                            162
Chicken Soft Tacos                       115
Chips and Fresh Tomato Salsa             110
Chicken Salad Bowl                       110
Canned Soda                              104
Side of Chips                            101
Veggie Burrito                            95
Barbacoa Burrito                          91
Veggie Bowl                               85
Carnitas Bowl                             68
Barbacoa Bowl                             66
Carnitas Burrito                          59
Steak Soft Tacos                          55
6 Pack Soft Drink                         54
Chips and Tomatillo Red Chili Salsa       48
Chicken Crispy Tacos                      47
Chips and Tomatillo Green Chili Salsa     43
Carnitas Soft Tacos                       40
Steak Crispy Tacos                        35
Chips and Tomatillo-Green Chili Salsa     31
Steak Salad Bowl                          29
Nantucket Nectar                          27
Barbacoa Soft Tacos                       25
Chips and Roasted Chili Corn Salsa        22
Izze                                      20
Chips and Tomatillo-Red Chili Salsa       20
Veggie Salad Bowl                         18
Chips and Roasted Chili-Corn Salsa        18
Barbacoa Crispy Tacos                     11
Barbacoa Salad Bowl                       10
Chicken Salad                              9
Veggie Soft Tacos                          7
Carnitas Crispy Tacos                      7
Veggie Salad                               6
Carnitas Salad Bowl                        6
Burrito                                    6
Steak Salad                                4
Crispy Tacos                               2
Salad                                      2
Bowl                                       2
Chips and Mild Fresh Tomato Salsa          1
Veggie Crispy Tacos                        1
Carnitas Salad                             1
Name: count, dtype: int64

### Step 4.

In [20]:
chip.groupby('item_name').item_price.sum().sort_values()

item_name
Chips and Mild Fresh Tomato Salsa           3.00
Veggie Crispy Tacos                         8.49
Carnitas Salad                              8.99
Crispy Tacos                               14.80
Salad                                      14.80
Bowl                                       29.60
Steak Salad                                35.66
Chips and Roasted Chili-Corn Salsa         43.02
Burrito                                    44.40
Veggie Salad                               50.94
Chips and Tomatillo-Red Chili Salsa        59.75
Carnitas Salad Bowl                        66.34
Izze                                       67.80
Chips and Roasted Chili Corn Salsa         67.85
Veggie Soft Tacos                          73.96
Carnitas Crispy Tacos                      77.96
Chips and Tomatillo-Green Chili Salsa      78.87
Chicken Salad                              81.09
Nantucket Nectar                           98.31
Barbacoa Salad Bowl                       106.40
Barbacoa Crispy Tacos                     120.21
Chips and Tomatillo Green Chili Salsa     132.75
Canned Soda                               137.34
Chips and Tomatillo Red Chili Salsa       147.50
Veggie Salad Bowl                         182.50
Side of Chips                             185.90
Barbacoa Soft Tacos                       250.46
Bottled Water                             302.56
Steak Salad Bowl                          343.59
6 Pack Soft Drink                         356.95
Steak Crispy Tacos                        357.34
Chips and Fresh Tomato Salsa              361.36
Carnitas Soft Tacos                       375.94
Canned Soft Drink                         438.75
Chicken Crispy Tacos                      472.13
Chips                                     494.34
Steak Soft Tacos                          536.05
Carnitas Burrito                          597.83
Barbacoa Bowl                             672.36
Carnitas Bowl                             736.71
Veggie Bowl                               867.99
Barbacoa Burrito                          894.75
Veggie Burrito                            934.77
Chicken Soft Tacos                       1108.09
Chicken Salad Bowl                       1228.75
Chips and Guacamole                      2201.04
Steak Bowl                               2260.19
Steak Burrito                            3851.43
Chicken Burrito                          5575.82
Chicken Bowl                             7342.73
Name: item_price, dtype: float64

### Step 5.

In [21]:
chip.groupby('item_name').item_price.describe()

,count,mean,std,min,25%,50%,75%,max
item_name,,,,,,,,
6 Pack Soft Drink,54.0,6.610185,8.831771e-01,6.49,6.490,6.49,6.49,12.98
Barbacoa Bowl,66.0,10.187273,1.260994e+00,8.69,9.250,9.25,11.75,11.75
Barbacoa Burrito,91.0,9.832418,1.139519e+00,8.69,9.250,9.25,11.28,11.75
Barbacoa Crispy Tacos,11.0,10.928182,2.800739e+00,8.99,9.250,9.25,11.75,18.50
Barbacoa Salad Bowl,10.0,10.640000,1.317616e+00,9.39,9.390,10.64,11.89,11.89
Barbacoa Soft Tacos,25.0,10.018400,1.191937e+00,8.99,9.250,9.25,11.75,11.75
Bottled Water,162.0,1.867654,1.547295e+00,1.09,1.500,1.50,1.50,15.00
Bowl,2.0,14.800000,1.046518e+01,7.40,11.100,14.80,18.50,22.20
Burrito,6.0,7.400000,9.729507e-16,7.40,7.400,7.40,7.40,7.40
Canned Soda,104.0,1.320577,5.189381e-01,1.09,1.090,1.09,1.09,4.36
Canned Soft Drink,301.0,1.457641,6.195359e-01,1.25,1.250,1.25,1.25,5.00
Carnitas Bowl,68.0,10.833971,3.622600e+00,8.99,9.250,9.25,11.75,35.25
Carnitas Burrito,59.0,10.132712,1.630111e+00,8.69,9.250,9.25,11.75,18.50
Carnitas Crispy Tacos,7.0,11.137143,3.263917e+00,8.99,9.120,9.25,11.75,17.98
Carnitas Salad,1.0,8.990000,NaN,8.99,8.990,8.99,8.99,8.99
Carnitas Salad Bowl,6.0,11.056667,1.290994e+00,9.39,10.015,11.89,11.89,11.89
Carnitas Soft Tacos,40.0,9.398500,6.845082e-01,8.99,9.250,9.25,9.25,11.75
Chicken Bowl,726.0,10.113953,2.489791e+00,8.19,8.750,8.75,11.25,32.94
Chicken Burrito,553.0,10.082857,2.810144e+00,8.19,8.750,8.75,11.25,35.00
Chicken Crispy Tacos,47.0,10.045319,2.260303e+00,8.49,8.750,8.75,11.25,17.50
Chicken Salad,9.0,9.010000,1.121194e+00,8.19,8.490,8.49,8.49,10.98
Chicken Salad Bowl,110.0,11.170455,3.986349e+00,8.75,8.750,8.75,11.25,22.50
Chicken Soft Tacos,115.0,9.635565,2.150383e+00,8.49,8.750,8.75,10.98,21.96
Chips,211.0,2.342844,6.519250e-01,1.99,2.150,2.15,2.15,6.45
Chips and Fresh Tomato Salsa,110.0,3.285091,4.075396e+00,2.29,2.390,2.95,2.95,44.25
Chips and Guacamole,479.0,4.595073,1.206059e+00,3.89,4.450,4.45,4.45,17.80
Chips and Mild Fresh Tomato Salsa,1.0,3.000000,NaN,3.00,3.000,3.00,3.00,3.00
Chips and Roasted Chili Corn Salsa,22.0,3.084091,6.289421e-01,2.95,2.950,2.95,2.95,5.90
Chips and Roasted Chili-Corn Salsa,18.0,2.390000,0.000000e+00,2.39,2.390,2.39,2.39,2.39
Chips and Tomatillo Green Chili Salsa,43.0,3.087209,6.285938e-01,2.95,2.950,2.95,2.95,5.90
Chips and Tomatillo Red Chili Salsa,48.0,3.072917,5.957258e-01,2.95,2.950,2.95,2.95,5.90
Chips and Tomatillo-Green Chili Salsa,31.0,2.544194,5.968572e-01,2.39,2.390,2.39,2.39,4.78
Chips and Tomatillo-Red Chili Salsa,20.0,2.987500,1.526413e+00,2.39,2.390,2.39,2.39,7.17
Crispy Tacos,2.0,7.400000,0.000000e+00,7.40,7.400,7.40,7.40,7.40
Izze,20.0,3.390000,4.556259e-16,3.39,3.390,3.39,3.39,3.39
Nantucket Nectar,27.0,3.641111,9.047241e-01,3.39,3.390,3.39,3.39,6.78
Salad,2.0,7.400000,0.000000e+00,7.40,7.400,7.40,7.40,7.40
Side of Chips,101.0,1.840594,1.220995e+00,1.69,1.690,1.69,1.69,13.52
Steak Bowl,211.0,10.711801,2.672417e+00,8.69,9.250,9.25,11.75,26.07
Steak Burrito,368.0,10.465842,2.571981e+00,8.69,8.990,9.25,11.75,27.75
Steak Crispy Tacos,35.0,10.209714,1.827732e+00,8.69,9.120,9.25,11.75,17.98
Steak Salad,4.0,8.915000,1.500000e-01,8.69,8.915,8.99,8.99,8.99
Steak Salad Bowl,29.0,11.847931,3.511170e+00,9.39,9.390,11.89,11.89,23.78
Steak Soft Tacos,55.0,9.746364,1.523743e+00,8.99,9.120,9.25,9.25,18.50
Veggie Bowl,85.0,10.211647,1.658164e+00,8.49,8.750,11.25,11.25,16.98
Veggie Burrito,95.0,9.839684,2.795877e+00,8.49,8.490,8.75,11.25,33.75
Veggie Crispy Tacos,1.0,8.490000,NaN,8.49,8.490,8.49,8.49,8.49
Veggie Salad,6.0,8.490000,0.000000e+00,8.49,8.490,8.49,8.49,8.49
Veggie Salad Bowl,18.0,10.138889,1.278275e+00,8.75,8.750,11.25,11.25,11.25
Veggie Soft Tacos,7.0,10.565714,3.090048e+00,8.49,8.620,8.75,11.25,16.98

### Step 6.

In [30]:
chip.groupby('order_id').item_name.size().sort_values(ascending=False).to_frame()

          item_name
order_id
926              23
1483             14
205              12
759              11
1786             11
...             ...
768               1
341               1
1048              1
94                1
1199              1

[1834 rows x 1 columns]

In [32]:
chip.loc[chip.order_id==chip.groupby('order_id').item_name.size().sort_values(ascending=False).index[0]]

,order_id,quantity,item_name,choice_description,item_price
2304,926,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Lettuce]]",9.25
2305,926,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
2306,926,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
2307,926,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
2308,926,1,Steak Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Lettu...",9.25
2309,926,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",8.75
2310,926,1,Steak Burrito,"[Roasted Chili Corn Salsa, [Rice, Cheese, Sour...",9.25
2311,926,1,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",8.75
2312,926,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Lettuce]]",8.75
2313,926,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream...",8.75
2314,926,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Rice, Sour Cream]]",8.75
2315,926,1,Steak Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",9.25
2316,926,1,Chicken Burrito,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",8.75
2317,926,1,Steak Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",9.25
2318,926,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
2319,926,1,Steak Bowl,"[Fresh Tomato Salsa, [Rice, Cheese]]",9.25
2320,926,1,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Cheese, Lettuce]]",8.75
2321,926,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Pinto Beans,...",8.75
2322,926,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Cheese]]",8.75
2323,926,1,Barbacoa Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",9.25
2324,926,1,Chicken Burrito,"[Tomatillo Red Chili Salsa, [Rice, Cheese, Sou...",8.75
2325,926,1,Steak Bowl,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",9.25
2326,926,1,Veggie Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",8.75

In [31]:
chip[chip.order_id==926]

,order_id,quantity,item_name,choice_description,item_price
2304,926,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Lettuce]]",9.25
2305,926,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
2306,926,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
2307,926,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
2308,926,1,Steak Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Lettu...",9.25
2309,926,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",8.75
2310,926,1,Steak Burrito,"[Roasted Chili Corn Salsa, [Rice, Cheese, Sour...",9.25
2311,926,1,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",8.75
2312,926,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Lettuce]]",8.75
2313,926,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream...",8.75
2314,926,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Rice, Sour Cream]]",8.75
2315,926,1,Steak Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",9.25
2316,926,1,Chicken Burrito,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",8.75
2317,926,1,Steak Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",9.25
2318,926,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
2319,926,1,Steak Bowl,"[Fresh Tomato Salsa, [Rice, Cheese]]",9.25
2320,926,1,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Cheese, Lettuce]]",8.75
2321,926,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Pinto Beans,...",8.75
2322,926,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Cheese]]",8.75
2323,926,1,Barbacoa Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",9.25
2324,926,1,Chicken Burrito,"[Tomatillo Red Chili Salsa, [Rice, Cheese, Sou...",8.75
2325,926,1,Steak Bowl,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",9.25
2326,926,1,Veggie Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",8.75

### Step 7.

### Step 8.

### Step 9.

### Step 10.

### Step 11.

### Step 12.

### Step 13.

### Step 14.

### Step 15.

### Step 16.

### BONUS: Create your own question and answer it.